spring.application.name=gym-gateway-api
server.port=8080


# RUTAS HACIA GYM-SOCIOS-API


spring.cloud.gateway.server.webmvc.routes[0].id=socios-route
spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/v1/socios/**

spring.cloud.gateway.server.webmvc.routes[1].id=planes-route
spring.cloud.gateway.server.webmvc.routes[1].uri=http://localhost:8081
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/v1/planes/**

spring.cloud.gateway.server.webmvc.routes[2].id=membresias-route
spring.cloud.gateway.server.webmvc.routes[2].uri=http://localhost:8081
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/v1/membresias/**


# RUTAS HACIA GYM-RESERVAS-API


spring.cloud.gateway.server.webmvc.routes[3].id=entrenadores-route
spring.cloud.gateway.server.webmvc.routes[3].uri=http://localhost:8082
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/api/v1/entrenadores/**

spring.cloud.gateway.server.webmvc.routes[4].id=clases-route
spring.cloud.gateway.server.webmvc.routes[4].uri=http://localhost:8082
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/api/v1/clases/**

spring.cloud.gateway.server.webmvc.routes[5].id=reservas-route
spring.cloud.gateway.server.webmvc.routes[5].uri=http://localhost:8082
spring.cloud.gateway.server.webmvc.routes[5].predicates[0]=Path=/api/v1/reservas/**
